# Generated by Django 4.0.4 on 2022-10-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasepayment1',
            name='duedate',
        ),
    ]
