# Generated by Django 4.0.4 on 2022-10-28 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_purchasedebit_alter_purchasepayment1_pymid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
    ]
