# Generated by Django 4.0.4 on 2022-10-29 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_vendor_cid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bill_item',
            new_name='purchasebill_item',
        ),
    ]
