# Generated by Django 4.0.4 on 2022-11-01 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_porder_item_purchaseorder_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedebit',
            name='billno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='supply',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
