# Generated by Django 4.0.4 on 2022-11-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_purchasedebit_billno_purchasedebit_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_statment',
            name='payments',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
