# Generated by Django 4.0.4 on 2022-11-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_vendor_statment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_statment',
            name='details',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
