# Generated by Django 4.0.4 on 2022-11-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_vendor_statment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_statment',
            name='details',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
