# Generated by Django 4.0.4 on 2022-11-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_vendor_statment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_statment',
            name='details2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
